name: project_app
description: A new Flutter project.

# Prevents accidental publishing to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning
version: 1.0.0+1

# Environment constraints
environment:
  sdk: '>=3.6.0 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  google_sign_in: ^6.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  syncfusion_flutter_gauges: ^28.1.41
  provider: ^6.1.2
  youtube_player_flutter: ^9.1.1
  uuid: ^4.5.1
  image_picker: ^1.1.2
  better_player_enhanced: ^0.0.5
  file_picker: ^9.2.1
  path_provider: ^2.1.5
  get: ^4.7.2
  video_player: ^2.9.3
  carousel_slider: ^5.0.0
  table_calendar: ^3.1.3

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true
  generate: true

  # Asset declarations
  assets:
    - assets/images/
    
