// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmUmrSiF11Fj2gFCGwuDV-Pr8vplysNOI',
    appId: '1:987260850340:web:49ab3fec9c90421a671631',
    messagingSenderId: '987260850340',
    projectId: 'diacare-app-8548c',
    authDomain: 'diacare-app-8548c.firebaseapp.com',
    storageBucket: 'diacare-app-8548c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxN8o9SD8wpvbtubghxTsUGGIEI9ybKBQ',
    appId: '1:987260850340:android:5479d80ccfd1b8a5671631',
    messagingSenderId: '987260850340',
    projectId: 'diacare-app-8548c',
    storageBucket: 'diacare-app-8548c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsqAKno_y1dr-H-wN87V-QYeU2XUiliyM',
    appId: '1:987260850340:ios:65b650c58fc9050f671631',
    messagingSenderId: '987260850340',
    projectId: 'diacare-app-8548c',
    storageBucket: 'diacare-app-8548c.firebasestorage.app',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsqAKno_y1dr-H-wN87V-QYeU2XUiliyM',
    appId: '1:987260850340:ios:65b650c58fc9050f671631',
    messagingSenderId: '987260850340',
    projectId: 'diacare-app-8548c',
    storageBucket: 'diacare-app-8548c.firebasestorage.app',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmUmrSiF11Fj2gFCGwuDV-Pr8vplysNOI',
    appId: '1:987260850340:web:146b453a702ff11c671631',
    messagingSenderId: '987260850340',
    projectId: 'diacare-app-8548c',
    authDomain: 'diacare-app-8548c.firebaseapp.com',
    storageBucket: 'diacare-app-8548c.firebasestorage.app',
  );
}
